

module.exports=[
	{
		id					:	1,
		accountId			:	'5412638410',
		customerType		:	'1',
		customerTypeName    :   'Advertiser',
		companyName			:	'Company 1',
		companyUrl			:	'http://www.company1.com',
		userName			:	'user_1',
		email				:	'contact@company1.com',
		taxonomyOwner		:	'CTM',
		taxonomyOwnerName	:	'Consortium',
		accountType			:	'SMP',
		isDataProvider		:	true,
		isMember			:	true,
		isPartner			:	true,
		isSubsidiary		:	false,
		minAmount			:	2000,
		agencyType			:	'5',
		agencyTypeName      :   '3rd Party Display',
		timezone			:	'54',
		currencies			:	['3','41'],
		defaultCurrency		:	'41',
		languagePref		:	'en_GB',
		lastUpdated         :   '2012-1-23',
		lastUpdatedBy       :   'user1'
	}
	, {
		id					:	2,
		accountId			:	'5412638411',
		customerType		:	'1',
		customerTypeName    :   'Advertiser',
		companyName			:	'Company 2',
		companyUrl			:	'http://www.company2.com',
		userName			:	'user_2',
		email				:	'contact@company2.com',
		taxonomyOwner		:	'CTM',
		taxonomyOwnerName	:	'Consortium',
		accountType			:	'SMP',
		isDataProvider		:	true,
		isMember			:	true,
		isPartner			:	true,
		isSubsidiary		:	false,
		minAmount			:	2000,
		agencyType			:	'5',
		agencyTypeName      :   '3rd Party Display',
		timezone			:	'54',
		currencies			:	['3','41'],
		defaultCurrency		:	'41',
		languagePref		:	'en_GB',
		lastUpdated         :   '2012-1-22',
		lastUpdatedBy       :   'user1'
	}
	, {
		id					:	3,
		accountId			:	'5412638412',
		customerType		:	'1',
		customerTypeName    :   'Advertiser',
		companyName			:	'Company 3',
		companyUrl			:	'http://www.company3.com',
		userName			:	'user_3',
		email				:	'contact@company3.com',
		taxonomyOwner		:	'CTM',
		taxonomyOwnerName	:	'Consortium',
		accountType			:	'SMP',
		isDataProvider		:	true,
		isMember			:	true,
		isPartner			:	true,
		isSubsidiary		:	false,
		minAmount			:	2000,
		agencyType			:	'5',
		agencyTypeName      :   '3rd Party Display',
		timezone			:	'54',
		currencies			:	['3','41'],
		defaultCurrency		:	'41',
		languagePref		:	'en_GB',
		lastUpdated         :   '2012-1-12',
		lastUpdatedBy       :   'user2'
	}
	, {
		id					:	4,
		accountId			:	'5689756901',
		customerType		:	'1',
		customerTypeName    :   'Advertiser',
		companyName			:	'Company A',
		companyUrl			:	'http://www.companya.com',
		userName			:	'a_user',
		email				:	'contact@companya.com',
		taxonomyOwner		:	'CTM',
		taxonomyOwnerName	:	'Consortium',
		accountType			:	'SMP',
		isDataProvider      :	true,
		isMember			:	true,
		isPartner			:	true,
		isSubsidiary        :	false,
		minAmount			:	5000,
		agencyType			:	'5',
		agencyTypeName      :   '3rd Party Display',
		timezone			:	'54',
		currencies			:	['3','41'],
		defaultCurrency     :	'41',
		languagePref        :	'en_GB',
		lastUpdated         :   '2012-1-20',
		lastUpdatedBy       :   'user1'
	}
];
