module.exports =
	{
		SUPPORTED_LANGUAGES :
		[
			{	id	:	"en_GB", text	:	"English-UK"	},
			{	id	:	"en_US", text	:	"English-US"	}
		],

		TAXONOMY_OWNERS :
		[
			{	id	:	"CTM", text	:	"Consortium"	},
			{	id	:	"ADN", text	:	"Ad Network"	},
			{	id	:	"DFT", text	:	"Default Taxonomy" 	}
		],

		ACCOUNT_TYPES :
		[
			{	id	:	"PN", text	:	"Pure Network"	},
			{	id	:	"SMP", text	:	"Self Managed Publisher"	},
			{	id	:	"VN", text	:	"Virtual Network"	}
		],

		AGENCY_TYPES :
		[
			{	id	:	"1", text	:	"Agency"	},
			{	id	:	"2", text	:	"Reseller"	},
			{	id	:	"3", text	:	"Technology Provider"	},
			{	id	:	"4", text	:	"Holding Company"	},
			{	id	:	"5", text	:	"3rd Party Display"	},
			{	id	:	"6", text	:	"3rd Party Performance"	},
			{	id	:	"7", text	:	"3rd Party Hybrid"	},
			{	id	:	"8", text	:	"3rd Party Creative"	}
		],

		TIMEZONES :
		[
			{	id	:	"1", text	:	"(GMT-12:00) International Date Line West"	},
			{	id	:	"5", text	:	"(GMT-11:00) Midway Island, Samoa"	},
			{	id	:	"21", text	:	"(GMT-10:00) Hawaii"	},
			{	id	:	"32", text	:	"(GMT-09:00) Alaska"	},
			{	id	:	"35", text	:	"(GMT-08:00) Pacific Time (US &amp; Canada); Tijuana"	},
			{	id	:	"52", text	:	"(GMT-07:00) Chihuahua, La Paz, Mazatlan"	},
			{	id	:	"54", text	:	"(GMT-07:00) Mountain Time (US &amp; Canada)"	},
			{	id	:	"71", text	:	"(GMT-07:00) Arizona"	},
			{	id	:	"75", text	:	"(GMT-06:00) Central Time (US &amp; Canada)"	},
			{	id	:	"76", text	:	"(GMT-06:00) Central America"	},
			{	id	:	"82", text	:	"(GMT-06:00) Guadalajara, Mexico City, Monterrey"	},
			{	id	:	"95", text	:	"(GMT-06:00) Saskatchewan"	},
			{	id	:	"116", text	:	"(GMT-05:00) Indiana (East)"	},
			{	id	:	"122", text	:	"(GMT-05:00) Bogota, Lima, Quito"	},
			{	id	:	"126", text	:	"(GMT-05:00) Eastern Time (US &amp; Canada)"	},
			{	id	:	"154", text	:	"(GMT-04:00) Caracas, La Paz"	},
			{	id	:	"171", text	:	"(GMT-04:00) Santiago"	},
			{	id	:	"184", text	:	"(GMT-04:00) Atlantic Time (Canada)"	},
			{	id	:	"196", text	:	"(GMT-03:00) Buenos Aires, Georgetown"	},
			{	id	:	"201", text	:	"(GMT-03:00) Greenland"	},
			{	id	:	"210", text	:	"(GMT-03:00) Brasilia"	},
			{	id	:	"218", text	:	"(GMT-02:00) Mid-Atlantic"	},
			{	id	:	"220", text	:	"(GMT-01:00) Azores"	},
			{	id	:	"222", text	:	"(GMT-01:00) Cape Verde"	},
			{	id	:	"228", text	:	"(GMT) Casablanca, Monrovia"	},
			{	id	:	"258", text	:	"(GMT) Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London"	},
			{	id	:	"261", text	:	"(GMT) Greenwich Mean Time"	},
			{	id	:	"290", text	:	"(GMT+01:00) West Central Africa"	},
			{	id	:	"291", text	:	"(GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna"	},
			{	id	:	"293", text	:	"(GMT+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague"	},
			{	id	:	"296", text	:	"(GMT+01:00) Brussels, Copenhagen, Madrid, Paris"	},
			{	id	:	"310", text	:	"(GMT+01:00) Sarajevo, Skopje, Warsaw, Zagre"	},
			{	id	:	"325", text	:	"(GMT+02:00) Cairo"	},
			{	id	:	"341", text	:	"(GMT+02:00) Jerusalem"	},
			{	id	:	"347", text	:	"(GMT+02:00) Harare, Pretoria"	},
			{	id	:	"348", text	:	"(GMT+02:00) Athens, Beirut, Istanbul, Minsk"	},
			{	id	:	"349", text	:	"(GMT+02:00) Bucharest"	},
			{	id	:	"351", text	:	"(GMT+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius"	},
			{	id	:	"375", text	:	"(GMT+03:00) Nairobi"	},
			{	id	:	"378", text	:	"(GMT+03:00) Baghdad"	},
			{	id	:	"380", text	:	"(GMT+03:00) Kuwait, Riyahd"	},
			{	id	:	"385", text	:	"(GMT+03:00) Moscow, St. Petersburg, Volgograd"	},
			{	id	:	"399", text	:	"(GMT+04:00) Baku, Tbilisi, Yerevan"	},
			{	id	:	"401", text	:	"(GMT+04:00) Abu Dhabi, Muscat"	},
			{	id	:	"417", text	:	"(GMT+05:00) Islamabad, Karachi, Tashkent"	},
			{	id	:	"420", text	:	"(GMT+05:00) Ekaterinburg"	},
			{	id	:	"430", text	:	"(GMT+06:00) Almaty, Novosibirsk"	},
			{	id	:	"433", text	:	"(GMT+06:00) Astana, Dhaka"	},
			{	id	:	"445", text	:	"(GMT+07:00) Bangkok, Hanoi, Jakarta"	},
			{	id	:	"448", text	:	"(GMT+07:00) Krasnoyarsk"	},
			{	id	:	"461", text	:	"(GMT+08:00) Beijing, Chongqing, Hong Kong, Urumqi"	},
			{	id	:	"462", text	:	"(GMT+08:00) Irkutsk, Ulaan Bataar"	},
			{	id	:	"471", text	:	"(GMT+08:00) Kuala Lumpur, Singapore"	},
			{	id	:	"472", text	:	"(GMT+08:00) Taipei"	},
			{	id	:	"477", text	:	"(GMT+08:00) Perth"	},
			{	id	:	"488", text	:	"(GMT+09:00) Seoul"	},
			{	id	:	"489", text	:	"(GMT+09:00) Osaka, Sapporo, Tokyo"	},
			{	id	:	"490", text	:	"(GMT+09:00) Yakutsk"	},
			{	id	:	"506", text	:	"(GMT+10:00) Vladivostok"	},
			{	id	:	"508", text	:	"(GMT+10:00) Brisbane"	},
			{	id	:	"510", text	:	"(GMT+10:00) Hobart"	},
			{	id	:	"515", text	:	"(GMT+10:00) Canberra, Melbourne, Sydney"	},
			{	id	:	"519", text	:	"(GMT+10:00) Guam, Port Moresby"	},
			{	id	:	"526", text	:	"(GMT+11:00) Magadan, Solomon Is., New Caledonia"	},
			{	id	:	"543", text	:	"(GMT+12:00) Auckland, Wellington"	},
			{	id	:	"544", text	:	"(GMT+12:00) Fiji, Kamchatka, Marshall Is."	},
			{	id	:	"556", text	:	"(GMT+13:00) Nuku'alofa"	}
		],

		CURRENCIES :
		[
			{	id	:	"3", text	:	"Albanian Lek (ALL)"	},
			{	id	:	"41", text	:	"Algerian Dinar (DZD)"	},
			{	id	:	"7", text	:	"Argentine Pesos (ARS)"	},
			{	id	:	"8", text	:	"Australian Dollar (AUD)"	},
			{	id	:	"13", text	:	"Bangladeshi Taka (BDT)"	},
			{	id	:	"20", text	:	"Brazilian Real (BRL)"	},
			{	id	:	"26", text	:	"Canadian Dollars (CAD)"	},
			{	id	:	"29", text	:	"Chilean Peso (CLP)"	},
			{	id	:	"30", text	:	"Chinese Renminbi (CNY)"	},
			{	id	:	"31", text	:	"Colombian Peso (COP)"	},
			{	id	:	"37", text	:	"Czech koruna (CZK)"	},
			{	id	:	"39", text	:	"Denmark Kroner (DKK)"	},
			{	id	:	"43", text	:	"Egyptian Pound (EGP)"	},
			{	id	:	"46", text	:	"Euros (EUR)"	},
			{	id	:	"58", text	:	"Hong Kong Dollar (HKD)"	},
			{	id	:	"62", text	:	"Hungarian Forint (HUF)"	},
			{	id	:	"69", text	:	"Iceland Krona (ISK)"	},
			{	id	:	"66", text	:	"Indian Rupee (INR)"	},
			{	id	:	"63", text	:	"Indonesian Rupiah (IDR)"	},
			{	id	:	"68", text	:	"Iranian Rial (IRR)"	},
			{	id	:	"64", text	:	"Israeli Shekels (ILS)"	},
			{	id	:	"72", text	:	"Jordanian Dinar (JOD)"	},
			{	id	:	"79", text	:	"Korean Won (KRW)"	},
			{	id	:	"80", text	:	"Kuwaiti Dinar (KWD)"	},
			{	id	:	"104", text	:	"Malaysian Ringgit (MYR)"	},
			{	id	:	"103", text	:	"Mexican Peso (MXN)"	},
			{	id	:	"91", text	:	"Moroccan Dirham (MAD)"	},
			{	id	:	"111", text	:	"New Zealand Dollar (NZD)"	},
			{	id	:	"107", text	:	"Nigerian Naira (NGN)"	},
			{	id	:	"109", text	:	"Norway Kroner (NOK)"	},
			{	id	:	"117", text	:	"Pakistani Rupee (PKR)"	},
			{	id	:	"114", text	:	"Peruvian Neuevo Sol (PEN)"	},
			{	id	:	"116", text	:	"Philippines Pesos (PHP)"	},
			{	id	:	"118", text	:	"Poland New Zloty (PLN)"	},
			{	id	:	"49", text	:	"Pounds Sterling (GBP)"	},
			{	id	:	"122", text	:	"Russian Ruble (RUB)"	},
			{	id	:	"124", text	:	"Saudi Riyal (SAR)"	},
			{	id	:	"129", text	:	"Singapore Dollars (SGD)"	},
			{	id	:	"170", text	:	"South African Rand (ZAR)"	},
			{	id	:	"128", text	:	"Swedish Kronor (SEK)"	},
			{	id	:	"28", text	:	"Swiss Franc (CHF)"	},
			{	id	:	"149", text	:	"Taiwan Dollar (TWD)"	},
			{	id	:	"141", text	:	"Thailand Bhat (THB)"	},
			{	id	:	"146", text	:	"Turkish Lira (TRY) "	},
			{	id	:	"153", text	:	"US Dollars (USD)"	},
			{	id	:	"151", text	:	"Ukraine Hryvnia (UAH)"	},
			{	id	:	"1", text	:	"United Arab Emirates Dirham (AED)"	},
			{	id	:	"157", text	:	"Vietnam Dong (VND)"	},
			{	id	:	"73", text	:	"Yen (JPY)"	}
		]
	};